name: Trigger auto deployment for tboostai-llm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tboostai-llm-AutoDeployTrigger-f6e43896-90db-4e30-b10b-8e7cd8a29c26.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TBOOSTAILLM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TBOOSTAILLM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TBOOSTAILLM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TBOOSTAILLM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TBOOSTAILLM_REGISTRY_PASSWORD }}
          containerAppName: tboostai-llm
          resourceGroup: tboostai-springcloud-prod
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


